---
- name: Update apt
  apt: update_cache=yes cache_valid_time=3600
  become: yes
  tags: update

- name: Install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - wget
    - curl

- include: oraclejdk.yml
  become: yes
  tags: java

- include: nexus.yml
  become: yes
  tags: nexus
